### PR TITLE
Return a richer set of run data

### PR DESCRIPTION
**Pull request by cryos**
I added this a few weeks ago, and forgot to push it. It is backwards
compatible with the old returned data as it just adds more. This is
intended to support a richer result page when looking at runs in a
catalog, and eventually when searching runs in a catalog.

### CODE REVIEW

**Review by tacaswell — APPROVED** [review]
Any reason to kee `def runs`?

**Comment by cryos** [comment]
Possibly not, I was just focused on adding richer runs, if the idea didn't pan out/we just want a simple list of run UIDs I wasn't sure if it might end up being useful. It is simpler and likely faster, yielding a smaller payload if we wanted it back.

**Comment by tacaswell** [comment]
We are also definitely going to need some sort of paging...

**Comment by cryos** [comment]
I know, I was talking with Stuart about it briefly the other day, and just perusing some of the paging widgets in Material UI yesterday. I need some bigger sample data sets to help exercise/flesh something out even if they are synthetic - at least a few hundred I think with date ranges/other searchable things.

**Comment by danielballan** [comment]
The first thing I did when we started down the path of using intake was add paging support to `RemoteCatalog`. There is more work to be done within databroker to support requesting arbitrary subsets of results from a Mongo cursor.

**Pull request merged**
