### PR TITLE
Add a very minimal viable product preview API

### PR DESCRIPTION
**Pull request by cryos**
This adds aiofiles as a dependency to serve files, and it assumes that
/tmp/ will have {uid}.png files with previews generated. This enables
some prototyping of the feature in the web interface, but it is only
intended as a temporary solution.

### CODE REVIEW

**Comment by tacaswell** [comment]
Is there an easy way to generate said previews?

**Comment by cryos** [comment]
I will see about adding something in a follow up commit, it is not that hard but some questions over triggering. Ideally upon first run or new runs it would generate a preview, they remain in a consistent spot.

**Comment by cryos** [comment]
I just pushed the script I was using @tacaswell to generate the thumbnails. As I said, there are lots and lots of improvements to be made, but the basic concept of generating PNGs at some point, using the uid to identify them, and serving them to the client are all of value.

**Review by danielballan — APPROVED** [review]
Looks good. CI was failing due to `flake8` complaints, so I took the liberty of running `black` to expediently address the whitespace issues, and then I addressed the more substantive warnings in follow-up commits.

**Comment by cryos** [comment]
Thanks for that, I wonder if the cookie cutter should be updated for the stuff it added that was failing? Another day perhaps, but the version stuff was all cookie cutter made.

**Pull request merged**
